export const ERROR_TYPE_CREATE_USER = "CREATE_USER_ERROR";
export const ERROR_TYPE_GET_USERS = "GET_USERS_ERROR";
export const ERROR_TYPE_DELETE_USER = "DELETE_USER_ERROR";
export const ERROR_TYPE_BAN_USER = "BAN_USER_ERROR";
