export enum Entities {
  MEDIA_TYPES = "media_tpyes",
  TAGS = "tags",
  PROJECTS = "projects",
  PROJECT_TAGS = "project_tags",
  GLOBAL_ROLES = "global_roles",
  USERS = "users",
  EDUCATIONS = "educations",
  SKILLS = "skills",
  USERS_SKILLS = "users_skills",
  PERMISSIONS = "permissions",
  GLOBAL_ROLE_PERMISSIONS = "global_role_permissions",
  PROJECT_ROLES = "project_roles",
  COLLABORATORS = "collaborators",
  EXPERIENCES = "experiences",
  TECHNOLOGIES = "technologies",
  PROJECTS_TECHNOLOGIES = "projects_technologies",
  PROJECT_ROLE_PERMISSIONS = "project_role_permissions",
  EXTERNAL_RESOURCES = "external_resources",
  USERS_TECHNOLOGIES = "users_technologies",
  PROJECTS_MEDIA = "projects_media",
  BLOGS = "blogs",
  BLOGS_MEDIA = "blogs_media",
}
