openapi: 3.0.3
info:
  title: Projects API
  version: 1.0.0

paths:
  /api/v1/projects/{id}:
    delete:
      summary: Delete a project
      description: Soft-delete a project by its ID. Requires a global role with DELETE_PROJECTS permission or a project role with DELETE_PROJECT permission.
      tags:
        - Projects
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 12
          required: true
          description: The ID of the project to delete
      responses:
        "200":
          description: Project successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: The project has been successfully deleted.
                  data:
                    type: array
                    items:
                      type: object
                    example: []
                  pagination:
                    type: object
                    properties:
                      offset:
                        type: integer
                        example: 0
                      limit:
                        type: integer
                        example: 0
                      count:
                        type: integer
                        example: 0
                      total:
                        type: integer
                        example: 0

        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

        "401":
          description: Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"

        "403":
          description: Forbidden, insufficient permissions or project is already deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenPermissionError"

        "404":
          description: Project with given ID does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectNotFoundError"

components:
  schemas:
    ValidationError:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: Invalid request
        data:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: field
              value:
                type: string
                example: ""
              msg:
                type: string
                example: "project 'id' must be a number"
              path:
                type: string
                example: id
              location:
                type: string
                example: params
        pagination:
          type: object
          properties:
            offset:
              type: integer
              example: 0
            limit:
              type: integer
              example: 0
            count:
              type: integer
              example: 0
            total:
              type: integer
              example: 0

    UnauthorizedError:
      type: object
      properties:
        status:
          type: integer
          example: 401
        message:
          type: string
          example: You must provide a token
        data:
          type: array
          items:
            type: object
        pagination:
          type: object
          properties:
            offset:
              type: integer
              example: 0
            limit:
              type: integer
              example: 0
            count:
              type: integer
              example: 0
            total:
              type: integer
              example: 0

    ForbiddenPermissionError:
      type: object
      properties:
        status:
          type: integer
          example: 403
        message:
          type: string
          example: You shall not pass!
        data:
          type: array
          items:
            type: object
        pagination:
          type: object
          properties:
            offset:
              type: integer
              example: 0
            limit:
              type: integer
              example: 0
            count:
              type: integer
              example: 0
            total:
              type: integer
              example: 0

    ProjectNotFoundError:
      type: object
      properties:
        status:
          type: integer
          example: 404
        message:
          type: string
          example: The entity with the given id does not exists.
        data:
          type: array
          items:
            type: object
          example: []
        pagination:
          type: object
          properties:
            offset:
              type: integer
              example: 0
            limit:
              type: integer
              example: 0
            count:
              type: integer
              example: 0
            total:
              type: integer
              example: 0
