openapi: 3.0.3
info:
  title: Roles API
  version: 1.0.0

paths:
  /api/v1/roles/permissions:
    get:
      summary: Retrieve a list of permissions
      description: >
        Fetch a paginated list of permissions.  
        Requires the role to have the global `LIST_PERMISSIONS` permission.
      tags:
        - Permissions
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: Maximum number of permissions to return. Must be a non-negative integer.
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Number of permissions to skip. Must be a non-negative integer.
        - in: query
          name: scope
          schema:
            type: string
            enum: [GLOBAL, PROJECT]
          example: GLOBAL
          description: >
            Filters the results by scope.  
            If provided, only permissions with the specified scope (`GLOBAL` or `PROJECT`) are returned.  
            If omitted, all permissions are returned.
      responses:
        "200":
          description: Permissions successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Permissions successfully retrieved.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 2
                        name:
                          type: string
                          example: UPDATE_USERS
                        scope:
                          type: string
                          example: GLOBAL
                        created_at:
                          type: string
                          format: date-time
                          example: 2025-09-22T17:52:36.367Z
                        updated_at:
                          type: string
                          format: date-time
                          example: 2025-09-22T17:52:36.367Z
                  pagination:
                    type: object
                    properties:
                      offset:
                        type: integer
                        example: 0
                      limit:
                        type: integer
                        example: 20
                      count:
                        type: integer
                        example: 3
                      total:
                        type: integer
                        example: 3

        "400":
          description: Validation error (invalid offset, limit, or onlyGlobal)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"

        "401":
          description: Missing or invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"

        "403":
          description: Forbidden, insufficient permissions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenPermissionError"
