CREATE TABLE IF NOT EXISTS global_roles (
    id SERIAL PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_global_roles_updated_at
BEFORE UPDATE ON global_roles
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();