CREATE TABLE IF NOT EXISTS skills (
    id SERIAL PRIMARY KEY,
    name_us VARCHAR(50) UNIQUE NOT NULL,
    name_es VARCHAR(50) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_skills_updated_at
BEFORE UPDATE ON skills
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();